"""Embed the two R5 manual recordings for file:// offline playback.

Usage: python build_parking_data.py PARALLEL.json PERPENDICULAR.json
"""

import hashlib
import json
import sys
from pathlib import Path


def pack(path: Path):
    raw = path.read_bytes()
    record = json.loads(raw)
    samples = record["samples"]
    assert len(samples) == record["sample_count"]
    runs = []
    for sample in samples:
        pair = [int(sample["motor_pwm"]), int(sample["servo_angle"])]
        if runs and runs[-1][:2] == pair:
            runs[-1][2] += 1
        else:
            runs.append(pair + [1])
    assert sum(run[2] for run in runs) == len(samples)
    return {
        "name": record["name"],
        "sha256": hashlib.sha256(raw).hexdigest(),
        "sample_count": record["sample_count"],
        "duration_sec": record["duration_sec"],
        "sample_hz": 20,
        "runs": runs,
    }


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    output = Path(__file__).with_name("parking-recordings.js")
    data = {"parallel": pack(Path(sys.argv[1])), "perpendicular": pack(Path(sys.argv[2]))}
    output.write_text("// Generated by build_parking_data.py from the saved R5 manual recordings.\n"
                      + "window.R5ParkingRecordings = " + json.dumps(data, separators=(",", ":")) + ";\n",
                      encoding="utf-8")
    for kind, item in data.items():
        print(f"{kind}: {item['sample_count']} samples, {len(item['runs'])} runs, SHA-256 {item['sha256']}")
